'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5466
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SisCoMi.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1350962045_checkin_key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350962045_checkin_key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350962307_keepassx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350962307_keepassx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350963463_Login_Manager() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350963463_Login Manager", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350963625_organization() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350963625_organization", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350963687_administrator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350963687_administrator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350964369_Log_Out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350964369_Log Out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350964632_Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350964632_Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350964853_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350964853_Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350964904_desktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350964904_desktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350964952_preferences_desktop_user_password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350964952_preferences-desktop-user-password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350965004_Database_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350965004_Database_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350965021_Database_Upload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350965021_Database-Upload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350965026_download_database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350965026_download-database", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350965159_security_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350965159_security yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350966379_BeOS_Help_book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350966379_BeOS_Help_book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350966437_system_software_installer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350966437_system-software-installer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350967056_calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350967056_calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350967090_alarmd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350967090_alarmd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350967678_administrator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350967678_administrator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350969715_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350969715_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350970899__trash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350970899_-trash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350970927_button_blue_repeat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350970927_button_blue_repeat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350971165_Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350971165_Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1350971740_print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1350971740_print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1353481746_edit_clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1353481746_edit-clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1353878295_gnome_searchtool() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1353878295_gnome-searchtool", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1365673661_camera_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1365673661_camera_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1365674082_Search_Male_User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1365674082_Search-Male-User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1365674096_preferences_desktop_personal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1365674096_preferences-desktop-personal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1365674473_37594() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1365674473_37594", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1365674675_Binoculars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1365674675_Binoculars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1365674703_iPhoto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1365674703_iPhoto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369855171_forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369855171_forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property christus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("christus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
